# Generated by Django 2.0.7 on 2018-07-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180720_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='author2',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
