# Generated by Django 2.0.7 on 2018-07-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180721_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author2',
            new_name='text',
        ),
    ]
